#!/usr/bin/env bash
# This script transfers a file from our client to a server
# Accepts 4 parameters:
#+    1. Path to the file to be transferred
#+    2. IP of the server to transfer to
#+    3. Username scp connects with
#+    4. Path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi