#!/usr/bin/env bash
# This script installs nginx on ubuntu
#+    Nginx should listen on port 80
#+    At its root when queried, it must return a page with "Hello World!"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /var/www/html;
    index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
