#!/usr/bin/env bash
# Configure nginx such that `/redirect_me` redirects as "301 Moved Permanently"

apt-get update
apt-get install -y nginx

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

nginx -t
service nginx restart
