#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains
#+ the string `Ceci n'est pas une page`

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

nginx -t
service nginx restart
