#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains
#+ the string `Ceci n'est pas une page`

apt-get update
apt-get install -y nginx

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 404;
    }
}
EOF

nginx -t
service nginx restart
