#!/usr/bin/env bash
# Configure Nginx such that for its response:
#+ The name of the custom HTTP header must be served by `X-Server-By`
#+ The value of the custom HTTP header must be the hostname of the server Nginx is running on

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
echo "Not Found!" > /var/www/html/404.html

SERVER_NAME=$(hostname)
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    add_header X-Served-By $SERVER_NAME;

    location /redirect_me {
        return 301 https://youtube.com/;
    }

    error_page 404 /404.html;
    location /404 {
        internal;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
