#!/usr/bin/env bash
# Configure Nginx to run and listen on port 80

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
