#!/usr/bin/env bash
# This script displays the content of the current directory in list format,
# displaying only the part of the name after the first dash, if present

for file in *; do
    if [[ $file != .* ]]; then
        filename=${file#*-}
        echo "$filename"
    fi
done
